/**
  * @file sht31_dev.h
  * @author generated by mrt-device utility 
  * @link [https://github.com/uprev-mrt/mrtutils/wiki/mrt-device]
  * @brief values and constants for the sht31 device registers
  * 
  */

#define SHT31_I2C_ADDRESS 0x44
#define SHT31_REG_ADDR_SIZE 1


/*******************************************************************************
  Register Addresses                                                                              
*******************************************************************************/



/*******************************************************************************
  Fields                                                                              
*******************************************************************************/


/*******************************************************************************
  Default Values                                                                              
*******************************************************************************/


/*******************************************************************************
  Flag Set/Clear/Check                                                                             
*******************************************************************************/

/**
  *@brief sets flags on device
  *@param dev ptr to sht31 device
  *@param reg ptr to register definition
  *@param mask mask of flags to set
  */
#define sht_set_flag(dev, reg, mask) regdev_set_flags(&(dev)->mRegDev,(reg), (mask))

/**
  *@brief clears flags on device
  *@param dev ptr to sht31 device
  *@param reg ptr to register definition
  *@param mask mask of flags to set
  */
#define sht_clear_flag(dev, reg, mask) regdev_clear_flags(&(dev)->mRegDev,(reg), (mask))

/**
  *@brief checks flags on device
  *@param dev ptr to sht31 device
  *@param reg ptr to register definition
  *@param mask mask of flags to set
  *@return true if all flags in mask are set 
  *@return false if any flags in mask are not set
  */
#define sht_check_flag(dev, reg, mask) regdev_check_flags(&(dev)->mRegDev,(reg), (mask))

/*******************************************************************************
  Field Getters                                                                              
*******************************************************************************/



/*******************************************************************************
  Field Setters                                                                              
*******************************************************************************/


/*******************************************************************************
  Configs                                                                            
*******************************************************************************/

