/**
  * @file sht31.c
  * @author generated by mrt-device utility 
  * @link [https://github.com/uprev-mrt/mrtutils/wiki/mrt-device]
  * @brief Device driver for sht31 device
  *
  */

#include "sht31.h"



/**
 * @brief initializes device
 * @param dev ptr to sht31 device
 * @return status 
 */
static mrt_status_t sht_init(sht31_t* dev)
{   
    /* Initialize Register Descriptors */


    /*user-block-init-start*/
    /*user-block-init-end*/

    return MRT_STATUS_OK;
}


mrt_status_t sht_init_i2c(sht31_t* dev, mrt_i2c_handle_t i2c)
{
    mrt_status_t status;

    status = init_i2c_register_device(&dev->mRegDev, i2c, SHT31_I2C_ADDRESS, SHT31_REG_ADDR_SIZE );

    sht_init(dev);


    /*user-block-init-i2c-start*/
    /*user-block-init-i2c-end*/
    
    return status;
}

mrt_status_t sht_test(sht31_t* dev)
{
    mrt_status_t status = MRT_STATUS_ERROR;
    /*user-block-test-start*/

    /*user-block-test-end*/
    return status;
}


/*user-block-bottom-start*/
/*user-block-bottom-end*/
